server:
  port: 8888
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: ${blog.datasource.driver-class-name}
      url: jdbc:mysql://${blog.datasource.host}:${blog.datasource.port}/${blog.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${blog.datasource.username}
      password: ${blog.datasource.password}
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.blog.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      blog:
        mapper: debug
        service: info
        controller: info
blog:

  jwt:

    user-secret-key: blog

    user-ttl: 28800000

    user-token-name: Authorization

  captcha:
    image:
      width: 150
      height: 50
      code-count: 4
      thickness: 3

      color-r: 249
      color-g: 251
      color-b: 220

  file:
    real-path: blog-server/src/main/resources/static/images #文件存储在项目中的位置
    url: http://ksgcrs.natappfree.cc/static/images/ #这里如果是和前端一块联调的话，需要改成我们的公网ip